INFO - 2023-06-20-17-04-41 - admin : (ERR000) Function started.
------------------------------------------------------------------------------------------------------------------------
ERROR - 2023-06-20-17-04-41 - admin : (ERR002) An exception occurred.
------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/reyhane/PythonProjects/Logger/./dorsa_logger.py", line 561, in wrapper
    fun(*args, **kwargs)
  File "/home/reyhane/PythonProjects/Logger/./dorsa_logger.py", line 581, in wrapper
    fun(*args, **kwargs)
  File "/home/reyhane/PythonProjects/Logger/Examples/example3.py", line 26, in test
    a = 2/0
ZeroDivisionError: division by zero
